### ISSUE TITLE
Kind of hard to play

### ISSUE THREAD

**Issue by martinrode** [teceP/tictactoe_golang#3]
```

=========================
|  'O'  |  'X'  |  ~  |   
-------------------------
|  'O'  |  ~  |  ~  |   
-------------------------
|  ~  |  ~  |  ~  |   
-------------------------
```

* Make sure the table is nicely aligned (use "tablewriter" -> there is plenty
* Label rows and columns so the user sees what he can enter
* Accept "A2" instead of "A/2"
* I have not played further, to see how your AI works (seems beatable though ...?)

**Comment by teceP** [comment]
Userinput-format is now changed to "A2" instead of "A/2".
Rendering is now done with a tablewriter.

I think the AI kinda works pretty well.
